In [3]:
import pandas as pd
import numpy as np


Есть ли связь между неграмотностью и рождаемостью? Для 94 стран, уровень неграмотности женщин в которых больше 5%, известны доля неграмотных среди женщин старше 15 (на 2003 год) и средняя рождаемость на одну женщину (на 2005 год).
Чему равен выборочный коэффициент корреляции Пирсона между этими двумя признаками? Округлите до четырёх знаков после десятичной точки.

In [17]:
data = pd.read_csv('illiteracy.txt', sep = '\t', header = 0)

In [4]:
data.head()

Country  Illit  Births
0  Albania   20.5    1.78
1  Algeria   39.1    2.44
2  Bahrain   15.0    2.34
3   Belize    5.9    2.97
4    Benin   73.5    5.60

In [20]:
data1 = data[['Illit','Births']]
data1.corr()

Illit    Births
Illit   1.000000  0.768663
Births  0.768663  1.000000

In [21]:
round(0.768663,4)

0.7687

Чему равен выборочный коэффициент корреляции Спирмена признаков из предыдущего вопроса? Округлите до четырёх знаков после десятичной точки.

In [22]:
data1.corr(method='spearman')

Illit    Births
Illit   1.000000  0.752962
Births  0.752962  1.000000

In [23]:
round(0.752962,4)

0.753

# Тест Корреляционный анализ

Для 61 большого города в Англии и Уэльсе известны средняя годовая смертность на 100000 населения (по данным 1958–1964) и концентрация кальция в питьевой воде (в частях на маллион). Чем выше концентрация кальция, тем жёстче вода. Города дополнительно поделены на северные и южные.
Есть ли связь между жёсткостью воды и средней годовой смертностью? Посчитайте значение коэффициента корреляции Пирсона между этими признаками, округлите его до четырёх знаков после десятичной точки.

In [3]:
data = pd.read_csv('water.txt', sep = '\t', header = 0)

In [4]:
data.head()

location        town  mortality  hardness
0    South        Bath       1247       105
1    North  Birkenhead       1668        17
2    South  Birmingham       1466         5
3    North   Blackburn       1800        14
4    North   Blackpool       1609        18

In [5]:
data1 = data[['mortality','hardness']]
round(data1.corr(),4)

mortality  hardness
mortality     1.0000   -0.6548
hardness     -0.6548    1.0000

В предыдущей задаче посчитайте значение коэффициента корреляции Спирмена между средней годовой смертностью и жёсткостью воды. Округлите до четырёх знаков после десятичной точки.

In [12]:
year_avg = data.groupby('town').mean()

In [14]:
round(year_avg.corr(method='spearman'),4)

mortality  hardness
mortality     1.0000   -0.6317
hardness     -0.6317    1.0000

Сохраняется ли связь между признаками, если разбить выборку на северные и южные города? Посчитайте значения корреляции Пирсона между средней годовой смертностью и жёсткостью воды в каждой из двух подвыборок, введите наименьшее по модулю из двух значений, округлив его до четырёх знаков после десятичной точки.

In [15]:
south = data.loc[data['location'] == 'South']
north = data.loc[data['location'] == 'North']

In [18]:
round(north[['mortality','hardness']].corr(),4)

mortality  hardness
mortality     1.0000   -0.3686
hardness     -0.3686    1.0000

In [19]:
round(south[['mortality','hardness']].corr(),4)

mortality  hardness
mortality     1.0000   -0.6022
hardness     -0.6022    1.0000

Среди респондентов General Social Survey 2014 года хотя бы раз в месяц проводят вечер в баре 203 женщины и 239 мужчин; реже, чем раз в месяц, это делают 718 женщин и 515 мужчин.

Посчитайте значение коэффициента корреляции Мэтьюса между полом и частотой похода в бары. Округлите значение до трёх знаков после десятичной точки.

In [22]:
a = 203
b = 718
c = 239
d = 515
MCC = (a*d - b*c)/((a+b) * (a+c) * (b+d) * (c+d))**0.5
round(MCC,3)

-0.109

В предыдущей задаче проверьте, значимо ли коэффициент корреляции Мэтьюса отличается от нуля. Посчитайте достигаемый уровень значимости; используйте функцию scipy.stats.chi2_contingency. Введите номер первой значащей цифры (например, если вы получили 5.5×10 −8, нужно ввести 8).

In [23]:
import scipy
from scipy.stats import chi2_contingency
obs = np.array([[203,718], [239,515]])
chi2_contingency(obs)

(19.40753078854304,
 1.0558987006638725e-05,
 1,
 array([[243.03402985, 677.96597015],
        [198.96597015, 555.03402985]]))

В предыдущей задаче давайте попробуем ответить на немного другой вопрос: отличаются ли доля мужчин и доля женщин, относительно часто проводящих вечера в баре? Постройте 95% доверительный интервал для разности долей, вычитая долю женщин из доли мужчин. Чему равна его нижняя граница? Округлите до четырёх знаков после десятичной точки.


In [24]:
fem = np.append(np.ones(203), np.zeros(718))
mal = np.append(np.ones(239), np.zeros(515))

In [25]:
# Фyнкция для расчета интервала для разности долей
def proportions_confint_diff_ind(sample1, sample2, alpha = 0.05):    
    z = scipy.stats.norm.ppf(1 - alpha / 2.)   
    p1 = float(sum(sample1)) / len(sample1)
    p2 = float(sum(sample2)) / len(sample2)
    
    left_boundary = (p1 - p2) - z * np.sqrt(p1 * (1 - p1)/ len(sample1) + p2 * (1 - p2)/ len(sample2))
    right_boundary = (p1 - p2) + z * np.sqrt(p1 * (1 - p1)/ len(sample1) + p2 * (1 - p2)/ len(sample2))
    
    return (left_boundary, right_boundary)

In [26]:
# Вызов метода
proportions_confint_diff_ind(mal, fem)

(0.053905233215813156, 0.13922183141523897)

In [27]:
round(0.053905233215813156,4)

0.0539

Проверьте гипотезу о равенстве долей любителей часто проводить вечера в баре среди мужчин и женщин. Посчитайте достигаемый уровень значимости, используя двустороннюю альтернативу. Введите номер первой значащей цифры (например, если вы получили 
5.5×10 −8
, нужно ввести 8).


In [ ]:
fem = np.append(np.ones(203), np.zeros(718))
mal = np.append(np.ones(239), np.zeros(515))

In [31]:
# вычисление z-статистики для 2 выборок
def proportions_diff_z_stat_ind(sample1, sample2):
    n1 = len(sample1)
    n2 = len(sample2)
    
    p1 = float(sum(sample1)) / n1
    p2 = float(sum(sample2)) / n2 
    P = float(p1*n1 + p2*n2) / (n1 + n2)
    
    return (p1 - p2) / np.sqrt(P * (1 - P) * (1. / n1 + 1. / n2))

In [ ]:
#  функция для расчета p-value для разности долей
def proportions_diff_z_test(z_stat, alternative = 'two-sided'):
    if alternative not in ('two-sided', 'less', 'greater'):
        raise ValueError("alternative not recognized\n"
                         "should be 'two-sided', 'less' or 'greater'")
    
    if alternative == 'two-sided':
        return 2 * (1 - scipy.stats.norm.cdf(np.abs(z_stat)))
    
    if alternative == 'less':
        return scipy.stats.norm.cdf(z_stat)

    if alternative == 'greater':
        return 1 - scipy.stats.norm.cdf(z_stat)

In [33]:
 proportions_diff_z_test(proportions_diff_z_stat_ind(fem, mal), alternative = 'two-sided')

8.153453089576601e-06

Посмотрим на данные General Social Survey 2014 года и проанализируем, как связаны ответы на вопросы "Счастливы ли вы?" и "Довольны ли вы вашим финансовым положением?"

Не доволен	Более или менее	Доволен
Не очень счастлив	197	111	33
Достаточно счастлив	382	685	331
Очень счастлив	110	342	333
Чему равно значение статистики хи-квадрат для этой таблицы сопряжённости? Округлите ответ до четырёх знаков после десятичной точки.
1 балл

In [34]:
obs = np.array([[197,111,33], [382,685,331], [110,342,333]])
chi2_contingency(obs)

(293.68311039689746,
 2.4964299580093467e-62,
 4,
 array([[ 93.08597464, 153.74722662,  94.16679873],
        [381.6251981 , 630.318542  , 386.0562599 ],
        [214.28882726, 353.93423138, 216.77694136]]))

In [35]:
round(293.68311039689746,4)

293.6831

Чему в предыдущей задаче равно значение коэффициента V Крамера для рассматриваемых признаков? Округлите ответ до четырёх знаков после десятичной точки.

In [40]:
xi = 293.68311039689746
n = 197 + 382 + 110 + 111 + 685 + 342 + 33 + 331 + 333

In [41]:
kramer = (xi/(n*2))**0.5

In [42]:
round(kramer,4)

0.2412

# Множественная проверка гипотез

Классификатор C4.5 и три его модификации: с оптимизацией гиперпараметра m, гиперпараметра cf и с одновременной оптимизацией обоих гиперпараметров. Эти четыре классификатора сравнивались на 14 наборах данных. На каждом датасете был посчитан AUC каждого классификатора. Данные записаны в файле:

AUCs.txt

Используя критерий знаковых рангов, проведите попарное сравнение каждого классификатора с каждым. Выберите два классификатора, различие между которыми наиболее статистически значимо

In [4]:
from scipy import stats
data = pd.read_csv('AUCs.txt', sep = '\t', header = 0)

In [52]:
data.head()

Unnamed: 0   C4.5  C4.5+m  C4.5+cf  C4.5+m+cf
0           adult (sample)  0.763   0.768    0.771      0.798
1            breast cancer  0.599   0.591    0.590      0.569
2  breast cancer wisconsin  0.954   0.971    0.968      0.967
3                      cmc  0.628   0.661    0.654      0.657
4               ionosphere  0.882   0.888    0.886      0.898

In [53]:
from itertools import combinations
combo = combinations(['C4.5','C4.5+m','C4.5+cf','C4.5+m+cf'], 2) 

In [54]:
for i in combo:
    print (i)

('C4.5', 'C4.5+m')
('C4.5', 'C4.5+cf')
('C4.5', 'C4.5+m+cf')
('C4.5+m', 'C4.5+cf')
('C4.5+m', 'C4.5+m+cf')
('C4.5+cf', 'C4.5+m+cf')


In [73]:
data_mod = data[['C4.5','C4.5+m','C4.5+cf','C4.5+m+cf']]
data_diff = pd.DataFrame()
data_diff['res_12'] = data['C4.5'] - data['C4.5+m']
data_diff['res_13'] = data['C4.5'] - data['C4.5+cf']
data_diff['res_14'] = data['C4.5'] - data['C4.5+m+cf']
data_diff['res_23'] = data['C4.5+m'] - data['C4.5+cf']
data_diff['res_24'] = data['C4.5+m'] - data['C4.5+m+cf']
data_diff['res_34'] = data['C4.5+cf'] - data['C4.5+m+cf']
data_diff.head()

res_12  res_13  res_14  res_23  res_24  res_34
0  -0.005  -0.008  -0.035  -0.003  -0.030  -0.027
1   0.008   0.009   0.030   0.001   0.022   0.021
2  -0.017  -0.014  -0.013   0.003   0.004   0.001
3  -0.033  -0.026  -0.029   0.007   0.004  -0.003
4  -0.006  -0.004  -0.016   0.002  -0.010  -0.012

In [74]:
m0 = 0

In [82]:
p = []

In [83]:
for i in range(len(data_diff.columns)):
    stat, p_val = stats.wilcoxon(data_diff.iloc[:,i] - m0)
    p.append(p_val)

In [84]:
p

[0.01075713311978963,
 0.861262330095348,
 0.015906444101703374,
 0.046332729793395394,
 0.3278256758446406,
 0.022909099354356588]

Сравнивая 4 классификатора между собой, мы проверили 6 гипотез. Давайте сделаем поправку на множественную проверку. Начнём с метода Холма. Сколько гипотез можно отвергнуть на уровне значимости 0.05 после поправки этим методом?

In [90]:
from statsmodels.sandbox.stats.multicomp import multipletests 

In [91]:
reject, p_corrected, a1, a2 = multipletests(p, alpha = 0.05, method = 'holm') 
p_corrected

array([0.0645428 , 0.86126233, 0.07953222, 0.13899819, 0.65565135,
       0.0916364 ])

Сколько гипотез можно отвергнуть на уровне значимости 0.05 после поправки методом Бенджамини-Хохберга?

In [93]:
reject, p_corrected, a1, a2 = multipletests(p, alpha = 0.05, method = 'fdr_bh') 
p_corrected

array([0.0458182 , 0.86126233, 0.0458182 , 0.06949909, 0.39339081,
       0.0458182 ])