In [1]:
import pandas as pd
import re

In [66]:
import numpy as np
import scipy as sc
from scipy.spatial import distance

In [3]:
# Скачайте файл с предложениями (sentences.txt).

In [4]:
file = open('Sentences.txt', 'r')
lines = file.readlines()
file.close()
lines = list(map(lambda x : x.lower(), lines))

In [5]:
#Произведите токенизацию, то есть разбиение текстов на слова.
# Для этого можно воспользоваться регулярным выражением, которое считает 
#разделителем любой символ, не являющийся буквой: re.split('[^a-z]', t). 
#Не забудьте удалить пустые слова после разделения.

In [6]:
words = list()

In [7]:
for line in range(0,len(lines)):
    temp_line = re.split('[^a-z]', lines[line])
    temp_line = list(filter(None, temp_line))
    words.append(temp_line)

In [8]:
words

[['in',
  'comparison',
  'to',
  'dogs',
  'cats',
  'have',
  'not',
  'undergone',
  'major',
  'changes',
  'during',
  'the',
  'domestication',
  'process'],
 ['as',
  'cat',
  'simply',
  'catenates',
  'streams',
  'of',
  'bytes',
  'it',
  'can',
  'be',
  'also',
  'used',
  'to',
  'concatenate',
  'binary',
  'files',
  'where',
  'it',
  'will',
  'just',
  'concatenate',
  'sequence',
  'of',
  'bytes'],
 ['a',
  'common',
  'interactive',
  'use',
  'of',
  'cat',
  'for',
  'a',
  'single',
  'file',
  'is',
  'to',
  'output',
  'the',
  'content',
  'of',
  'a',
  'file',
  'to',
  'standard',
  'output'],
 ['cats',
  'can',
  'hear',
  'sounds',
  'too',
  'faint',
  'or',
  'too',
  'high',
  'in',
  'frequency',
  'for',
  'human',
  'ears',
  'such',
  'as',
  'those',
  'made',
  'by',
  'mice',
  'and',
  'other',
  'small',
  'animals'],
 ['in',
  'one',
  'people',
  'deliberately',
  'tamed',
  'cats',
  'in',
  'a',
  'process',
  'of',
  'artificial',
  's

In [9]:
clear_words = list()
for i in range(0,len(words)):
    for word in words[i]:
        clear_words.append(word)

In [10]:
clear_words

['in',
 'comparison',
 'to',
 'dogs',
 'cats',
 'have',
 'not',
 'undergone',
 'major',
 'changes',
 'during',
 'the',
 'domestication',
 'process',
 'as',
 'cat',
 'simply',
 'catenates',
 'streams',
 'of',
 'bytes',
 'it',
 'can',
 'be',
 'also',
 'used',
 'to',
 'concatenate',
 'binary',
 'files',
 'where',
 'it',
 'will',
 'just',
 'concatenate',
 'sequence',
 'of',
 'bytes',
 'a',
 'common',
 'interactive',
 'use',
 'of',
 'cat',
 'for',
 'a',
 'single',
 'file',
 'is',
 'to',
 'output',
 'the',
 'content',
 'of',
 'a',
 'file',
 'to',
 'standard',
 'output',
 'cats',
 'can',
 'hear',
 'sounds',
 'too',
 'faint',
 'or',
 'too',
 'high',
 'in',
 'frequency',
 'for',
 'human',
 'ears',
 'such',
 'as',
 'those',
 'made',
 'by',
 'mice',
 'and',
 'other',
 'small',
 'animals',
 'in',
 'one',
 'people',
 'deliberately',
 'tamed',
 'cats',
 'in',
 'a',
 'process',
 'of',
 'artificial',
 'selection',
 'as',
 'they',
 'were',
 'useful',
 'predators',
 'of',
 'vermin',
 'the',
 'domesticat

In [11]:
#Составьте список всех слов, встречающихся в предложениях. 
#Сопоставьте каждому слову индекс от нуля до (d - 1), где d — число различных слов в предложениях. 
#Для этого удобно воспользоваться структурой dict.

In [12]:
from collections import Counter

In [65]:
d = len(Counter(clear_words).keys())
n = len(lines)

In [14]:
hash_map = {}

In [15]:
j = 0
for word in clear_words:
    if word in hash_map:
        continue
    else:
        hash_map[word] = j
        j = j +1

In [178]:
hash_map

{'in': 0,
 'comparison': 1,
 'to': 2,
 'dogs': 3,
 'cats': 4,
 'have': 5,
 'not': 6,
 'undergone': 7,
 'major': 8,
 'changes': 9,
 'during': 10,
 'the': 11,
 'domestication': 12,
 'process': 13,
 'as': 14,
 'cat': 15,
 'simply': 16,
 'catenates': 17,
 'streams': 18,
 'of': 19,
 'bytes': 20,
 'it': 21,
 'can': 22,
 'be': 23,
 'also': 24,
 'used': 25,
 'concatenate': 26,
 'binary': 27,
 'files': 28,
 'where': 29,
 'will': 30,
 'just': 31,
 'sequence': 32,
 'a': 33,
 'common': 34,
 'interactive': 35,
 'use': 36,
 'for': 37,
 'single': 38,
 'file': 39,
 'is': 40,
 'output': 41,
 'content': 42,
 'standard': 43,
 'hear': 44,
 'sounds': 45,
 'too': 46,
 'faint': 47,
 'or': 48,
 'high': 49,
 'frequency': 50,
 'human': 51,
 'ears': 52,
 'such': 53,
 'those': 54,
 'made': 55,
 'by': 56,
 'mice': 57,
 'and': 58,
 'other': 59,
 'small': 60,
 'animals': 61,
 'one': 62,
 'people': 63,
 'deliberately': 64,
 'tamed': 65,
 'artificial': 66,
 'selection': 67,
 'they': 68,
 'were': 69,
 'useful': 70,
 'p

In [64]:
#Создайте матрицу размера n * d, где n — число предложений.
#Заполните ее: элемент с индексом (i, j) в этой матрице должен быть равен
#количеству вхождений j-го слова в i-е предложение.
#У вас должна получиться матрица размера 22 * 254.

In [20]:
matrix  = np.arange(n*d).reshape(n,d)

In [56]:
for i in range(0,n):
    for j in range(0,d):
        count = 0
        key = list(hash_map.keys())[list(hash_map.values()).index(j)]
        for k in range(0,len(words[i])):
            if (words[i][k]==key):
                count = count + 1
        matrix[i][j] = count
        

In [63]:
print (matrix)

[[1 1 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [0 0 1 ... 1 1 1]]


In [ ]:
#Найдите косинусное расстояние от предложения в самой первой строке
#до всех остальных с помощью функции scipy.spatial.distance.cosine.
#Какие номера у двух предложений, ближайших к нему по этому расстоянию?
#Эти два числа и будут ответами на задание.

In [93]:
result = []


In [94]:
for i in range(0,n):
    result.append(distance.cosine(matrix[0][:],matrix[i][:]))

In [103]:
for i in range(0,n):
    print (result[i])

0.0
0.9527544408738466
0.8644738145642124
0.8951715163278082
0.7770887149698589
0.9402385695332803
0.7327387580875756
0.9258750683338899
0.8842724875284311
0.9055088817476932
0.8328165362273942
0.8804771390665607
0.8396432548525454
0.8703592552895671
0.8740118423302576
0.9442721787424647
0.8406361854220809
0.956644501523794
0.9442721787424647
0.8885443574849294
0.8427572744917122
0.8250364469440588
